# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation
APPLY_FIXES: all # all, none, or list of linter keys
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - PYTHON_FLAKE8 # because there is no support for FlakeHeaven
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: poetry.lock
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .git
  - .github
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
